[workspace]
resolver = "2"
members = [
    "bindgen",
    "fixtures",
    "fixtures/errors",
    "fixtures/destroy",
    "fixtures/objects",
    "fixtures/name-case",
    "fixtures/regressions/*"
]

[workspace.dependencies]
uniffi = "=0.28.0"
uniffi_testing = "=0.28.0"
uniffi_macros = "=0.28.0"
uniffi_build = { version = "=0.28.0", features=["builtin-bindgen"] }
uniffi_bindgen = "=0.28.0"
uniffi_meta = "=0.28.0"
uniffi_udl = "=0.28.0"
